config/routes.rb
Rails.application.routes.draw do
  get 'users/sign_in'
  get 'users/sign_up' => "users#sign_up", :as => 'user_signup'
  #get 'users/sign-in' => "users#sign-in", :as => 'users_signin'
  get 'catalogs/main' => "catalogs#main", :as => 'main_abc'

  resources :catalogs do
    resources :polls, :galleries, :articles do
      resources :comments, only: [:index, :new, :create]
    end

  end
end



=begin
member do
        # Thumbnail Routes
        get :new_comment
        post :comments

        # Medias Routes
        get :new_media
        post :medias
        
        # Thumbnail Routes
        get :new_thumbnail
        post :thumbnails
      end

      collection do
        get :all_comments
        get :all_medias
        get :all_thumbnails
      end
=end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    enum status: { created: 0, composed: 1, published: 2, recomposed: 3, republished: 4, unpublished: 5, rejected: 6}

     #has_many :media as :mediable
     #has_many :thumbnail as :thumbnailable
     has_many :comments,  as: :commentable 
     
end

app/models/catalog.rb
class Catalog < ApplicationRecord
    enum ctype: { article: 0, poll: 1, gallery: 2 }
    validates :name, presence: true
    validates :ctype, inclusion: { in: %w(article poll gallery),
     message: "%{value} is not valid catalog_type" }
     has_many :articles 
     has_many :polls
     has_many :galleries 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    enum :status, { created: 0, composed: 1, published: 2, recomposed: 3,
     republished: 4, unpublished: 5, rejected: 6}
end

app/models/medium.rb
class Medium < ApplicationRecord
  belongs_to :mediable, polymorphic: true
end

app/models/poll.rb
class Poll < ApplicationRecord
    enum :status, { created: 0, composed: 1, published: 2, recomposed: 3,
     republished: 4, unpublished: 5, rejected: 6}

end

app/models/thumbnail.rb
class Thumbnail < ApplicationRecord
  belongs_to :thumbnailable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article/comments_controller.rb
class Articles::CommentsController < CommentsController
before_action :set_commentable

private
def set_commentable
    @commentable = Article.find(params[:article_id])

end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_catalog
  before_action :set_article, only: [:edit, :show, :destory, :new_comment, :comments, :all_comments]

  def index 
    @articles = @catalog.articles.all
  end    

  def new 
    @article = @catalog.articles.new
  end   

  def create 
    @article = @catalog.articles.new(article_params)
    if @article.save 
      redirect_to [@catalog,@article]
    else 
      render 'new'
    end 
  end   

  def show; end

  def edit;end

  def update 
    @article = @catalog.articles.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to [@catalog,@article] 
    else 
      render 'edit'
    end
  end

  def destroy 
    @article = @catalog.articles.find(params[:id])
    @article.destroy
  end

  # Initializes empty comment object with commentable object(@article)
  # /catalogs/:catalog_id/articles/:article_id/new_comment
  # GET
  def new_comment
    @comment = Comment.new
  end


  # Creates a comment for Article
  # /catalogs/:catalog_id/articles/:article_id/comments
  # POST
  def comments
    @comment = Comment.new(comment: params[:comments][:comment], commentable: @article)
    if @comment.save
    else
    end
  end

  # Returns all comments for commentable
  # /catalogs/:catalog_id/articles/:article_id/all_comments
  # GET
  def all_comments
    @comments = @article.comments
  end
  
  
  


  private

  def article_params
    params.require(:article).permit(:title, :long_description, :short_description, :status  )
  end

  def set_catalog
    @catalog = Catalog.find(params[:catalog_id])
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
    @catalogs = Catalog.all
   # render json: @catalogs
    #resond to do |format|
     # format.json @catalogs
    #end
  end
  
  def new
    @catalog = Catalog.new
  end

  # def show
  #   @catalog = Catalog.find(params[:id])
  # conf  @items = []
  #   @items = @catalog.articles if @catalog.ctype == 'article'
  #   @items = @catalog.galleries if @catalog.ctype == 'gallery'
  #   @items = @catalog.polls if @catalog.ctype == 'poll'    
  # end

  def create 
    @catalog = Catalog.new(catalog_params)
    if @catalog.save
      flash[:success] = "Catalog is created sucessfull!"
       redirect_to @catalog   
    else
     render 'new'
    end
  end

  def show 
    @catalog = Catalog.find(params[:id])
  end

  def edit
    @catalog = Catalog.find(params[:id])
  end

  def update 
    @catalog = Catalog.find(params[:id])
    if @catalog.update(catalog_params)
      flash[:success] = "Catalog is updated successfull!" 
      redirect_to @catalog
    else
      render 'edit' 
    end 

  end  
  def destroy
    @catalog = Catalog.find(params[:id])
    @catalog.destroy
    flash[:success] = "Catalog Deleted Successfull!"
    redirect_to @catalog
  end
    private
      def catalog_params
        params.require(:catalog).permit(:name, :ctype)
      end  
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable
  def index
    
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(comment: params[:comment][:comment], commentable: @commentable)
    if @comment.save
      redirect_to catalog_articles_path(@catalog, @commentable)
    else
      Rails.logger.debug @comment.errors.full_messages
      redirect_to new_catalog_article_comment_path(@catalog, @commentable)
    end
  end

  private

  def set_commentable
    @commentable = Article.find(params[:article_id]) if params[:article_id].present? 
    @commentable = Poll.find(params[:poll_id]) if params[:poll_id].present? 
    @commentable = Gallery.find(params[:gallery_id]) if params[:gallery_id].present? 
    @catalog = Catalog.find(params[:catalog_id])
  end
  
  
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
    def index
        @catalog = Catalog.find(params[:catalog_id])
        @polls =
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="container">

<%= form_for [@catalog, @article] do |f| %>
  Title: <%= f.text_field :title %><br />
  Short_Description : <%= f.text_field :short_description %><br />
  Long_Description : <%= f.text_field :long_description %><br />
  Status : <%= f.text_field :status %><br /> 
  
  <%= f.submit "Update " %>
<% end %>
<%= link_to 'Back', catalog_articles_path(@catalog) %>

</div>

app/views/articles/index.html.erb
<div class="container">
  <h1> All Articles </h1>
  <h2> <%= link_to 'Create New Articles', new_catalog_article_path(@catalog,@article) %> </h2>
  <div>
    <% @articles.each  do |a| %>
      <p> Title : <%= a.title %> </p> <br />
      <p> Short Description : <%= a.short_description %> </p> <br />
      <p> Long Description : <%= a.long_description %> </p> <br />
      <p> Status : <%= a.status %> </p> <br />
      <button class="primary btn-success"> <%= link_to  "edit", edit_catalog_article_path(@catalog,a) %> </button>
      <button class="primary btn-danger"> <%= link_to 'delete', catalog_article_path(@catalog,a),
      method: :delete, data:{ confirm: 'are you sure ?'} %> </button>
      <hr>
      <%= link_to  "Create Comment", new_catalog_article_comment_path(@catalog, a) %>
      <hr>
      <h3> Comments </h3>
      <% a.comments.each do |comment| %>
        <p><%= comment.comment %></p><br>
      <% end-%>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
<br>
<h1> Creation of New Article </h1>
<% flash.each do |message_type, success| %>
 <div class="alert alert-<%= message_type%>"> <%= success %> </div>
<% end %>


<%= form_for :article, url: catalog_articles_path,local: true  do |f| %>
  Title: <%= f.text_field :title  ,:required => true%><br />
  Short_description : <%= f.text_field :short_description,:required => true%><br />
  Long_description : <%= f.text_area :long_description,  size: "colsxrols",  :required => true %> <br />
  Status: <%= f.text_field :status  ,:required => true%><br />
  <%
=begin%>
 Date : <%= datetime_select :published_at, :birth_date %> <br /> 
<%
=end%>
  <br/>

  <%= f.submit "Save " %>
<% end %>


<%= link_to 'Back', catalog_articles_path %>

</div>

app/views/articles/new_comment.html.erb
<%#= form_for(comments_catalog_article_path(@catalog, @article)) do |f| %>
<%= form_tag(path: "/catalogs/#{@catalog.id}/articles/#{@article.id}/comments", method: :post, remote: true) do %>
  <%= label_tag(:comment) %><br/>
  <%= text_area_tag(:comment) %>
  <%= submit_tag "Create" %>
<% end %>

app/views/articles/show.html.erb
<div class="container">
  <%= link_to  "Back", catalog_articles_path %><br/><br/>
  <p><%= @article.title.titleize %> | 
  <%= @article.short_description %> | 
  <%= @article.long_description %> </p>    
  
  <hr/>
  <%= link_to  "Create Comments", new_catalog_article_comment_path(@catalog, @article) %>
  <br/>
  <p><b> Comments </b></p>
  <% @article.comments.each do |comment| %>
    <p><%= comment.comment%></p><br/>
  <% end -%>
  
</div>

app/views/catalogs/edit.html.erb
<div class="container">

<%= form_for @catalog do |f| %>
  Name: <%= f.text_field :name %><br />
  Type : <%= f.text_field :ctype %><br />
  
  <%= f.submit "Update " %>
<% end %>
<%= link_to 'Back', catalogs_path %>

</div>

app/views/catalogs/index.html.erb
<div class="container">
<br>
<h3 class="align-center"> <%= link_to "Catalogs List" , main_abc_path%> </h3>
<br>
<%= link_to('' , { :action => 'main' }) %>

<h4> <%= link_to "Catalog Create", new_catalog_path%> </h4>


<table class="table">
<thead class="thead-dark">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Created At</th>
    <th>Updated At</th>
    <th> Edit </th>
    <th> Show </th>
    <th> Delete </th>
  </tr>
</thead>
<tbody>
<% @catalogs.each do |catalog| %>
  <tr>
    <td> <%= link_to catalog.name, catalog_path(catalog)%>    </td> 
    <td> <%= catalog.ctype %> </td>
    <td> <%= catalog.created_at %> </td>
    <td> <%= catalog.updated_at %> </td>
    <td> <%= link_to 'Edit', edit_catalog_path(catalog)%> </td>
    
    <td> <%= link_to 'Show', catalog_path(catalog)%>  </td>
   
    <td> <%= link_to 'Delete', catalog_path(catalog),
    method: :delete, data: {confirm: 'Are you sure?'}
    %> </td>
   
  </tr>
  <% end -%>
</tbody>

</table>   
</div>

app/views/catalogs/main.html.erb
<h1> This is the first page </h1>

app/views/catalogs/new.html.erb
<div class="container">
<br>
<h1> Creation of New Catalog </h1>
<% flash.each do |message_type, success| %>
 <div class="alert alert-<%= message_type%>"> <%= success %> </div>
<% end %>


<%= form_for :catalog, url: catalogs_path,local: true  do |f| %>
  Name: <%= f.text_field :name  ,:required => true%><br />
  Type : <%= f.text_field :ctype ,:required => true%><br />
  
  <%= f.submit "Save " %>
<% end %>


<%= link_to 'Back', catalogs_path %>

</div>

app/views/catalogs/show.html.erb
<div class="container">
    <h3><%= @catalog.name.titleize %> | <%= @catalog.ctype %></h3>    
    <%
=begin%>
 <%= link_to 'Back', catalogs_path %> 
<%
=end%>
<%= render "shared/back" %>

<%= link_to "Create #{@catalog.ctype.titleize}", new_catalog_article_path(@catalog) %> 
 

</div>           

app/views/comments/new.html.erb
<%= form_for([@catalog, @commentable, @comment]) do |f| %>
    <%= f.label(:comment) %><br/>
    <%= f.text_area(:comment) %>
    <%= f.submit("Create")%>
<% end %>